---
- name: Run query script
  script: >
    query_ova.py
    "{{ entity_type }}"
    "{{ ovirt_query_ova_path }}"
    "{{ list_directory }}"
  args:
    executable: "{{ ansible_python_interpreter }}"
  register: extraction_result
