language: java
jdk: [oraclejdk8]
os: [linux]
addons: {firefox: latest}
script: [mvn install -Dwebdriverextensions.disabledbrowsers=chrome -Dchrome.binary.path=/usr/bin/chromium-browser
    -Ptravis-ci]
before_script: ['export DISPLAY=:99.0', sh -e /etc/init.d/xvfb start, mkdir -p /tmp/webdriverextensions-maven-plugin/cache,
  mkdir -p /tmp/webdriverextensions-maven-plugin/drivers, mkdir -p /tmp/webdriverextensions-maven-plugin/temp]
branches:
  only: [webdriverextensions/webdriverextensions-137-origin]
