language: java
sudo: false
jdk: oraclejdk8
install: true
script: ./travis.sh
env: [BROWSER=PHANTOM_JS, BROWSER=FIREFOX]
cache:
  directories: [$HOME/.m2/repository]
branches:
  only: [dgageot/simplelenium-27-MAVEN_FORK_TEST]
