language: java
before_install: [sudo apt-get -qq update, 'sudo apt-get -qq install libstdc++6:i386
    libgcc1:i386 zlib1g:i386 libncurses5:i386 libsdl1.2debian:i386 libv4l-dev', 'wget
    https://javacv.googlecode.com/files/javacv-0.4-cppjars.zip', unzip -qq javacv-0.4-cppjars.zip,
  unzip -o -qq javacv-cppjars/opencv-2.4.4-linux-x86_64.jar, unzip -o -qq javacv-cppjars/ffmpeg-1.1.3-linux-x86_64.jar,
  'export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PWD}/com/googlecode/javacv/cpp/linux-x86_64',
  sudo ldconfig]
branches:
  only: [sagioto/LipReading-18-MAVEN_PARALLEL_TEST]
