language: java
jdk: [openjdk6, openjdk7]
services: postgresql
before_script: [psql -c 'create database myapp_test;' -U postgres, psql -f 'jirm-spring/src/test/sql/create-test-db.sql'
    -U postgres -d 'myapp_test']
branches:
  only: [agentgt/jirm-49-origin]
