sudo: required
language: java
jdk: [openjdk7, oraclejdk8]
matrix:
  include:
  - env: NAME="Matcher Server"
    before_script: ['curl http://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf
        --output map/osm/oberbayern.osm.pbf', travis_wait docker exec barefoot-database
        /bin/bash -i /mnt/map/osm/import.sh, 'mvn --quiet -Dexec.executable="echo"
        -Dexec.args=''-n ${project.version}'' --non-recursive exec:exec > version',
      'docker run -t -d --net=host --name="barefoot-matcher" -v ${PWD}:/mnt/barefoot
        --workdir /mnt/barefoot barefoot-map java -jar target/barefoot-`cat version`-matcher-jar-with-dependencies.jar
        --geojson config/server.properties config/oberbayern.properties', 'until sudo
        lsof -Pi :1234 -sTCP:LISTEN -t; do sleep 1; done', docker logs barefoot-matcher]
    script: [python util/submit/batch.py --host localhost --port 1234 --file src/test/resources/com/bmwcarit/barefoot/matcher/x0001-015.json,
      python util/submit/batch.py --host localhost --port 1234 --file src/test/resources/com/bmwcarit/barefoot/matcher/x0001-001.json]
    after_failure: [docker logs barefoot-matcher]
  - env: NAME="Python Map Tools"
    install: true
    before_script: [until docker exec barefoot-database sudo --user=postgres -- psql
        --command='select 1;'; do sleep 1; done]
    script: docker exec barefoot-database /bin/bash /mnt/map/tools/test/run.sh
  - env: NAME="Java Formatting"
    jdk: oraclejdk8
    before_install: true
    install: mvn formatter:format
    before_script: true
    script: [git diff --exit-code]
    after_failure: true  To fix this failure automatically, run "mvn formatter:format"
      on your code using Java 8+
services: [docker]
before_install: [docker build -t barefoot-map ./map, sudo service postgresql stop,
  'docker run -t -d --net=host --name="barefoot-database" -v ${PWD}/map/:/mnt/map
    barefoot-map']
before_script: ['curl http://download.geofabrik.de/europe/germany/bayern/oberbayern-latest.osm.pbf
    --output map/osm/oberbayern.osm.pbf', travis_wait docker exec barefoot-database
    /bin/bash -i /mnt/map/osm/import.sh]
script: [mvn test --batch-mode --errors]
branches:
  only: [bmwcarit/barefoot-159-MAVEN_FORK_TEST]
