dist: trusty
language: java
sudo: false
jdk: [oraclejdk9, oraclejdk11]
install: true
env: null
global:
- {secure: iI7IpfDtS+LUyS2yNuRCR3KelNyvBHuoMQ3gb1UNmR5SSL7jO/p3olQWrQROs28FJ+dpE3lHyIjoHrebKQGJHHAgTG2XWxn+G3fDsf+wSSFSLoDGj0o2SgGXooBbR2dccnNZHCyQaOyE2cIPWaOxrQZFE4No70LQB4mrP/gdkoc=}
matrix:
  include:
  - {jdk: oraclejdk8, env: STRUTS_IT=true}
script: ['if [ "$STRUTS_IT" == "true" ]; then ./mvnw clean verify org.jacoco:jacoco-maven-plugin:report
    org.jacoco:jacoco-maven-plugin:report-integration org.eluder.coveralls:coveralls-maven-plugin:report
    -Ptravis-coveralls -DskipAssembly -B; else if [ "$TRAVIS_PULL_REQUEST" != "false"
    ]; then ./mvnw test -DskipAssembly -B; else ./mvnw test -DskipAssembly -Dupdate-impact
    -B; fi; fi;']
cache:
  directories: [$HOME/.m2]
branches:
  only: [apache/struts-507-MAVEN_FORK_TEST]
