jdk: [openjdk7, oraclejdk7, oraclejdk8]
language: ruby
rvm: [1.9.3]
env:
  global: {secure: X49it0ImkmAwo1X1gX4H22xQfa8pwTKxpjvvIFI21Deif17VEpaIn0QB1cZ4PyAqv44Y7sXbMIiUrq53Lge5TqgigvNM6KjQsvDr6r+6kPhPwfLHS90V0GRkNF49sMpq68J88rbwMqM44l2fpR4Ke0KBjWraqIQ8XgAdAKnCP/o=}
before_install: [sudo apt-get update]
install: ['wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz',
  tar xfvz protobuf-2.6.1.tar.gz, cd protobuf-2.6.1 && ./configure --prefix=/usr &&
    make && sudo make install && cd -, sudo apt-get install nodejs, gem install bundler]
before_script: [.utility/before_script.sh]
script: [.utility/build.sh]
after_success: [.utility/publish-artifacts.sh]
after_failure: [cat target/surefire-reports/*output.txt]
branches:
  only: [zk1931/jzab-220-MAVEN_FORK_TEST]
