language: java
cache:
  directories: [~/.m2]
git: {depth: false}
env:
  global:
  - {secure: erPk0ACAA2A4i+ik4RKhLS6xAWRqC03KuaQ8dD91Oy8fsIRJdTu7w+woATRW2rESak6qHsp0aZvzEz9WaIrxFxpn/8DEPPgXQK/Hz3bm+zySTwELy0HCEO+ATEbdGMjpSoGlDRUS3eu0zBGOfZHI7Jp3LQYiycZO7PIzaxWo2UI=}
before_install: [gem install public_suffix -v 3.0.3]
matrix:
  include:
  - jdk: oraclejdk11
    env: [DESC="tests by oracle"]
    script: [mvn clean verify]
  - jdk: openjdk11
    env: [DESC="tests by openjdk"]
    script: [mvn clean verify]
  - jdk: oraclejdk11
    env: [DESC="static analysis"]
    script: ['mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test install
        sonar:sonar -Dsonar.projectKey=damianszczepanik_cucumber-reporting']
after_success: ['curl -Os https://uploader.codecov.io/latest/linux/codecov', chmod
    +x codecov, ./codecov]
deploy:
  provider: pages
  repo: damianszczepanik/damianszczepanik.github.io
  target_branch: master
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: target/demo/
  verbose: true
  true: {branch: master}
addons:
  sonarcloud: {organization: damianszczepanik, token: $SONAR_TOKEN}
  branches: [master]
branches:
  only: [damianszczepanik/cucumber-reporting-1020-origin]
