language: java
jdk: [oraclejdk11]
before_install: openssl aes-256-cbc -K $encrypted_7d767fcac9aa_key -iv $encrypted_7d767fcac9aa_iv
  -in settings-obf.xml.enc -out settings-obf.xml -d
after_success: mvn -T 1C deploy --settings settings-obf.xml
branches:
  only: [jzy3d/jzy3d-api-195-origin]
