language: java
jdk: [openjdk8, openjdk12]
install: true
branches:
  only: [lemire/externalsortinginjava-41-MAVEN_FORK_TEST]
script: mvn clean test jacoco:report
after_success: ['mvn coveralls:report']
