language: java
jdk: [oraclejdk8]
before_script: ['me.j360.disboot.websocket.echo "MAVEN_OPTS=''-Xmx1024m -XX:MaxPermSize=256m''"
    > ~/.mavenrc']
after_success: ['mvn clean cobertura:cobertura', 'bash <(curl -s https://codecov.io/bash)']
install: travis_wait 30 mvn install
branches:
  only: [xuminwlt/j360-boot-app-all-3-origin]
