language: bash
sudo: required
services: [docker]
script: ['docker run -it -v $(pwd):/root/sources -w /root/sources maven:3.3.3-jdk-8
    mvn clean install']
branches:
  only: [CodeStory/fluent-http-157-origin]
