dist: trusty
language: java
cache:
  directories: [$HOME/.m2]
jdk: [oraclejdk8]
before_script: ['export DISPLAY=:99.0', jdk_switcher use openjdk11]
script: mvn -T 1C -s .travis.settings.xml -B -Djava8.home=/usr/lib/jvm/java-8-oracle
  -Djava11.home=/home/travis/openjdk11 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  -Dgpg.skip=true install
before_install: [cp .travis.settings.xml $HOME/.m2/settings.xml, 'wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
    && . ./install-jdk.sh -F 11 --target /home/travis/openjdk11 --os linux-x64', jdk_switcher
    use oraclejdk8, echo "MAVEN_OPTS='-Xmx1024m'" > ~/.mavenrc, sudo apt-get install
    jq, 'echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne ''/-BEGIN
    CERTIFICATE-/,/-END CERTIFICATE-/p'' | sudo tee -a /etc/ssl/certs/ca-', 'wget
    -O ~/codacy-coverage-reporter-assembly-latest.jar https://github.com/codacy/codacy-coverage-reporter/releases/download/4.0.1/codacy-coverage-reporter-4.0.1-assembly.jar',
  '/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile
    --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16']
install: mvn -T 1C -s .travis.settings.xml -B -Djava8.home=/usr/lib/jvm/java-8-oracle
  -Djava11.home=/home/travis/openjdk11 -DskipTests=true -Dmaven.javadoc.skip=true
  -Dspotbugs.skip=true -Dcheckstyle.skip=true -Dgpg.skip=true -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
  install
after_success: ['${JAVA_HOME}/bin/java -jar ~/codacy-coverage-reporter-assembly-latest.jar
    report -l Java -r ./spf4j-jacoco-aggregate/target/site/jacoco-aggregate/jacoco.xml']
branches:
  only: [zolyfarkas/spf4j-63-origin]
