---
- include_tasks: "{{ item }}.yml"
  with_items:
    - host-os
    - av-setup
    - cinderlib-setup

- name: Ensure Python3 is installed for CentOS/RHEL8 hosts
  yum:
    name: python3
    state: present
  when: el_ver|int >= 8

- name: Setup Ansible Python interpreter
  set_fact:
    ansible_python_interpreter : "{{ '/usr/bin/python3'
        if (fc_ver|int > 0 or el_ver|int >= 8)
        else '/usr/bin/python2' }}"
