- name: Check for firewalld rules file
  stat:
    path: "{{ role_path }}/vars/{{ firewald_rules_file }}"
  register: firewalld_rule_file_stat
  delegate_to: localhost

- block:
  - name: Include firewalld rules
    include_vars:
      file: "{{ firewald_rules_file }}"
      name: cluster_vars
    register: include_cluster_vars

  # We need to ignore errors in case the service doesn't exist.
  - name: Enable firewalld rules
    firewalld:
      port: "{{ item.port | default(omit) }}"
      service: "{{ item.service | default(omit) }}"
      permanent: yes
      immediate: yes
      state: enabled
    with_items: "{{ cluster_vars.host_deploy_firewalld_rules | default([]) }}"
    when: "cluster_vars is defined and not include_cluster_vars.failed | default(false)"

  when: firewalld_rule_file_stat.stat.exists
