---
- name: Setup the configuration file
  template:
    src: libvirt-guests.j2
    dest: /etc/sysconfig/libvirt-guests
    backup: yes

- name: Start libvirt-guests service and ensure its enabled
  service:
    name: libvirt-guests
    state: started
    enabled: yes
